import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/global/navbar/Navbar";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <div className="bg-gradient-to-r from-cyan-500 to-blue-200 min-h-screen">
          <header className="fixed top-0 left-0 w-full flex justify-center items-center z-10 ">
            <Navbar />
          </header>
          {children}
        </div>
      </body>
    </html>
  );
}
